In [8]:

import numpy as np

In [9]:
#Q.1 Numpy Array construction Create 5 by 10 array with all elements random between 50 and 100

In [10]:
a = np.random.randint(50,101,size=(5,10))

In [6]:
a

array([[84, 95, 83, 50, 68, 74, 71, 71, 75, 82],
       [65, 90, 53, 66, 53, 56, 74, 70, 70, 99],
       [58, 55, 68, 97, 77, 57, 50, 78, 79, 81],
       [93, 87, 87, 83, 58, 61, 96, 52, 65, 90],
       [78, 59, 63, 92, 85, 96, 66, 57, 60, 65]])

In [11]:
#Q.3 Create a numpy array that contain integers i such that 0<i<100 and 2^i has the last digit 6

In [12]:
b=np.arange(1,100)
j=2**b
b=b[(j%10)==6]

In [13]:
b

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

In [14]:
#Q.4 Create an array of first 10 powers of 2

In [15]:
c=2**np.arange(10)

In [16]:
c

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [18]:
#Q.5 Use all the slicing methods for each dimension of the given mutidimensional array First of all, create a mutidimensional array as shown in the figure below and then write your code to answer from 1) to 5)

In [19]:
d=np.arange(0,6)

In [20]:
e=np.array([d,d+10,d+20,d+30,d+40,d+50])

In [21]:
e

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [23]:
#1) retrieve 3,4 as shown in red box

In [28]:
e[0,3:5]

array([3, 4])

In [24]:
#2) retrieve all elements of column indexed with 2 (output should be 2,12,22,32, 42, 52

In [27]:
e[0:,2]

array([ 2, 12, 22, 32, 42, 52])

In [25]:
#3) retrieve row indexed with 2 and a row indexed with 4 at a time

In [29]:
e[2:5:2,0:5:2]

array([[20, 22, 24],
       [40, 42, 44]])

In [26]:
#4) retrieve element 33

In [30]:
np.array(e[3,3])

array(33)

In [31]:
#5) retrieve the elements as shown in the green box

In [32]:
e[4:,4:]

array([[44, 45],
       [54, 55]])