<a href="https://colab.research.google.com/github/nachiket-15/Introduction_to_Data_Visualization/blob/main/numpy_learning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Essential Training**

**What is Numpy ?**

*NumPy (Numerical Python) is a powerful library in python which is used extensively for numerical and mathematical calculations*

**Applications**

*1.Multidimensional Arrays: NumPy provides a numpy.ndarray object, which is a multi-dimensional array. These arrays can be used to represent matrices, tensors, or any other multi-dimensional data structures.*

*2.Mathematical Operations: NumPy allows you to perform element-wise operations on arrays, making it easy to apply mathematical functions to entire datasets without the need for explicit loops.*

*3.Linear Algebra: NumPy provides a set of functions for linear algebra operations, such as matrix multiplication, inversion, determinant calculation, and more.*

*4.Broadcasting: NumPy supports broadcasting, which is a powerful mechanism that allows NumPy to work with arrays of different shapes and sizes during arithmetic operations.*

*5.Data Analysis and Manipulation: NumPy is often used in combination with other libraries like Pandas for data analysis and manipulation. It provides a foundation for working with numerical data efficiently.*


In [1]:
import numpy as np

In [92]:
list=[1,2,3,4,5,6,7]
arr=np.array(list)
print(arr)

arr=np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [3]:
#Third parameter is step/diff
arr1=np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]


In [4]:
#Third parameter - no of elements
arr2=np.linspace(1,10,5)
print(arr2)

[ 1.    3.25  5.5   7.75 10.  ]


In [5]:
print(arr2.dtype)
print(arr1.dtype)


float64
int64


In [6]:
arr3=np.random.rand(10)
print(arr3)

[0.27748257 0.69997352 0.77447942 0.08348119 0.53177751 0.31437686
 0.94560571 0.78738404 0.35676808 0.52322219]


In [7]:
# NumPy function in Python that generates an array of random numbers in the half-open interval [0.0, 1.0).
arr4=np.random.rand(4,4)
print(arr4)

[[0.27449443 0.23707596 0.58134238 0.53187348]
 [0.86083986 0.27125655 0.5074541  0.58191775]
 [0.54811439 0.52842294 0.22424186 0.1208183 ]
 [0.66417214 0.82909625 0.42297186 0.33842444]]


In [8]:
arr5=np.random.randint(1,100,25)
print(arr5)

[24 25 52 41 23 13 30 91 71 63 28 40 34 18  5 18 53 84 74 66 15 57 36 39
 72]


In [9]:
arr5

array([24, 25, 52, 41, 23, 13, 30, 91, 71, 63, 28, 40, 34, 18,  5, 18, 53,
       84, 74, 66, 15, 57, 36, 39, 72])

In [94]:
arr6=np.zeros(6)
print(arr6)
print(arr6.dtype)

[0. 0. 0. 0. 0. 0.]
float64


In [11]:
print(arr5.shape)#Provides size of each dimension of array
print(arr5.ndim)#No of dimensions of numpy array
print(arr4.shape)
print(arr4.ndim)

(25,)
1
(4, 4)
2


In [93]:
# Creating a 1-dimensional array
arr_1d = np.array([1, 2, 3])
print(arr_1d.shape)  # Output: (3,)

# Creating a 2-dimensional array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.shape)  # Output: (2, 3)

# Creating a 3-dimensional array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d.shape)  # Output: (2, 2, 2)

(3,)
(2, 3)
(2, 2, 2)


In [12]:
arr7=np.zeros((4,4),dtype=int)
print(arr7)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
arr8=np.ones(5,dtype=int)
print(arr8)

[1 1 1 1 1]


In [14]:
arr9=np.ones((5,5),dtype=int)
print(arr9)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [99]:
arr10=np.empty(6)
print(arr10)
print(arr10.dtype)


arr10.fill(10)
print(arr10)



[10. 10. 10. 10. 10. 10.]
float64
[10. 10. 10. 10. 10. 10.]


In [16]:
arr11=np.full(7,10)
print(arr11)

[10 10 10 10 10 10 10]


In [97]:
# (start,stop,no of samples to be generated)

arr12=np.linspace((1,2),(10,20),10)
print(arr12)


[[ 1.  2.]
 [ 2.  4.]
 [ 3.  6.]
 [ 4.  8.]
 [ 5. 10.]
 [ 6. 12.]
 [ 7. 14.]
 [ 8. 16.]
 [ 9. 18.]
 [10. 20.]]


In [18]:
#full(dimension,element to be filled)
arr13=np.full((2,2,2),10)#tensor is a 3d array
print(arr13)


[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]


In [19]:
#The shape attribute returns a tuple representing the dimensions of the array
print(arr12.shape)
print(arr13.shape)
print(arr12.size)
print(arr13.size)
print(arr13.ndim)

(10, 2)
(2, 2, 2)
20
8
3


In [100]:
#The ndim attribute returns the number of dimensions of the array.

arr_1d = np.array([1, 2, 3])
print(arr_1d.ndim)  # Output: 1

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.ndim)  # Output: 2


1
2


In [101]:

first_list=[1,2,3,4,5,6,7,8,9,10]
first_array=np.array(first_list)
print(first_array)

second_list=[1,2,3,-1.23,50,128000.56,4.56]
second_array=np.array(second_list)
print(second_array)
#print(second_array.dtype)


third_list=['Ann',111111,'Peter',111112,'Susan',111113,'John',111114]
third_array=np.array(third_list)
print(third_array)




[ 1  2  3  4  5  6  7  8  9 10]
[ 1.0000000e+00  2.0000000e+00  3.0000000e+00 -1.2300000e+00
  5.0000000e+01  1.2800056e+05  4.5600000e+00]
['Ann' '111111' 'Peter' '111112' 'Susan' '111113' 'John' '111114']


In [102]:
first_tuple=(5, 10, 15, 20, 25, 30)
array_from_tuple=np.array(first_tuple)
print(array_from_tuple)


print("\nTensor")
multi_dim_list=[[[0,1,2], [3,4,5]], [[6,7,8],[9,10,11]]]
arr_from_multi_dim_list=np.array(multi_dim_list)
print(arr_from_multi_dim_list)

[ 5 10 15 20 25 30]

Tensor
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


Adding , Removing & Sorting Elements

In [106]:
first_arr=np.array([1, 2, 3, 5])
print(first_arr)

# np.insert is a NumPy function that allows you to insert values along a given axis before a specified index.
# numpy.insert(arr, obj:Index before which values should be inserted, values, axis=None)

new_first_arr=np.insert(first_arr,3,4)
print(new_first_arr)


arr = np.array([1,2,3,4,5])
new_arr = np.insert(arr,2,[10,11])
print(new_arr)

[1 2 3 5]
[1 2 3 4 5]
[ 1  2 10 11  3  4  5]


In [23]:
second_arr=np.array([1,2,3,4])
print(second_arr)

new_second_arr=np.append(second_arr,5)
print(new_second_arr)

[1 2 3 4]
[1 2 3 4 5]


In [24]:
third_arr=np.array([1,2,3,4,5])
print(third_arr)

del_arr=np.delete(third_arr,4)
print(del_arr)

[1 2 3 4 5]
[1 2 3 4]


In [107]:
integers_arr=np.random.randint(0,20,20)
print(integers_arr)
print(np.sort(integers_arr))

print("\n")

integers_2dim_arr=np.array([[3, 2, 5,7, 4], [5, 0, 8,3, 1]])
print(integers_2dim_arr)
print(np.sort(integers_2dim_arr))

[11 19  4 17 13  7 17 17  1 11  0  6 16  3 16 18  3 14 16  5]
[ 0  1  3  3  4  5  6  7 11 11 13 14 16 16 16 17 17 17 18 19]


[[3 2 5 7 4]
 [5 0 8 3 1]]
[[2 3 4 5 7]
 [0 1 3 5 8]]


In [26]:
colors=np.array(['orange','green','yellow','white','black','pink','blue','red'])
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']


Copies & Views


In [27]:
#id() is often referred to as address of an object in python
students_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])

students_ids_number_reg=students_ids_number
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))

id of students_ids_number 137811007279568
id of students_ids_number_reg 137811007279568


In [108]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[2000 2222 1313 1414 1515 1616 1717 1818]
[2000 2222 1313 1414 1515 1616 1717 1818]


In [29]:
#Creating a copy
students_ids_number_cp=students_ids_number.copy()
print(students_ids_number_cp)
print(students_ids_number_cp==students_ids_number)

[1111 2222 1313 1414 1515 1616 1717 1818]
[ True  True  True  True  True  True  True  True]


In [30]:
print ("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_cp",id(students_ids_number_cp))

id of students_ids_number 137811007279568
id of students_ids_number_cp 137811007279952


In [31]:
#Any change made in previous array doesnt gets reflected in copy array
students_ids_number[0]=1000
print ("original: ", students_ids_number)
print("copy: ",students_ids_number_cp)

original:  [1000 2222 1313 1414 1515 1616 1717 1818]
copy:  [1111 2222 1313 1414 1515 1616 1717 1818]


In [109]:
#.view() method is used to create a new array object with the same data as the original array but with a different shape
#or data type. The .view() method does not create a new copy of the data;
#it creates a view or a "window" into the existing data.

students_ids_number_v=students_ids_number.view()

students_ids_number_v[0]=2000
#Changes made to one array will affect the other since they share the same underlying data:
print("original: ", students_ids_number)
print("view:",students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
view: [2000 2222 1313 1414 1515 1616 1717 1818]


In [33]:
print(students_ids_number_cp.base)
print(students_ids_number_v.base)


None
[2000 2222 1313 1414 1515 1616 1717 1818]


Main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

**Reshaping Arrays**

In [34]:
shape_array=np.arange(1,13)
print(shape_array)

print("\n")
nshape_array=np.reshape(shape_array,(6,2))# 6 rows , 2 columns
print(nshape_array)
print("\n")

nshape_array=np.reshape(shape_array,(4,3))# 4 rows , 3 columns
print(nshape_array)

print("\n")

nshape_array=np.reshape(shape_array,(3,2,2))
print(nshape_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [35]:
#Converting 2D array into 1D using reshape,flatten & ravel

sixth_arr=np.array([[1,2],[3,4],[5,6]])
print(sixth_arr)
print("\n")

seventh_arr_flat=np.reshape(sixth_arr,-1)
print("array_using_reshape",seventh_arr_flat)

eighth_arr_flat=sixth_arr.flatten()
print("\narr_using_flatten:",eighth_arr_flat)

ninth_arr_rav=sixth_arr.ravel()
print("\narr_using_ravel:",ninth_arr_rav)


#Reshape refers to chnaging shape of an array w/o changing data
#Flattening involves converting multi-dimensional array into one dimension
#FLatten returns copy of original array.Modifying flattened array does not changes original array
#Ravel returns reference/view of original array . Modifying ravelled array changes original array


[[1 2]
 [3 4]
 [5 6]]


array_using_reshape [1 2 3 4 5 6]

arr_using_flatten: [1 2 3 4 5 6]

arr_using_ravel: [1 2 3 4 5 6]


In [36]:
eighth_arr_flat[0]=100
print("sixth_arr:",sixth_arr)
print("eighth_arr_flat:",eighth_arr_flat)



sixth_arr: [[1 2]
 [3 4]
 [5 6]]
eighth_arr_flat: [100   2   3   4   5   6]


In [37]:
ninth_arr_rav[0]=300
print("ninth_arr_rav:",ninth_arr_rav)
print("sixth_arr:",sixth_arr)

ninth_arr_rav: [300   2   3   4   5   6]
sixth_arr: [[300   2]
 [  3   4]
 [  5   6]]


**Indexing and Slicing**

In [38]:
twodim_arr=np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
print(twodim_arr[1,1])
print(twodim_arr[1])

5
[4 5 6 7]


In [40]:
threedim_arr=np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [41]:
print(threedim_arr[0,2,3])
print("Indexing from end: ")
print(threedim_arr[2,-1,-1])

13
Indexing from end: 
59


In [42]:
onedim_arr=np.arange(10)
print(onedim_arr)
#Slicing [start,stop)
print(onedim_arr[2:6])
print(onedim_arr[:5])

#Last 3
print(onedim_arr[-3:])

#[Start,stop,step)
print(onedim_arr[::2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[0 1 2 3 4]
[7 8 9]
[0 2 4 6 8]


In [43]:
print(twodim_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
#Trimming 0th row and 0th column
print(twodim_arr[1:,1:])

#Printing 1st row
print(twodim_arr[1,:])

#Printing 2nd column
print(twodim_arr[:,2])


[[ 5  6  7]
 [ 9 10 11]]
[4 5 6 7]
[ 2  6 10]


In [45]:
first_arr=np.arange(1,11)
second_arr=np.arange(11,21)
print("first_arr",first_arr)
print("second_arr",second_arr)
con_arr=np.concatenate((first_arr,second_arr))
con_arr

first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr [11 12 13 14 15 16 17 18 19 20]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
third_2darr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(third_2darr)
fourth_2darr=np.array([[11,12,13,14,15], [16,17,18,19,20]])
print(fourth_2darr)

con2d_arr = np.concatenate((third_2darr,fourth_2darr),axis=1)
con2d_arr

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [47]:
st_arr = np.stack((first_arr,second_arr),axis=0)
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [48]:
st_arr = np.stack((first_arr,second_arr),axis=1)
st_arr

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19],
       [10, 20]])

In [49]:
hst_arr=np.hstack((first_arr,second_arr))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
vst_arr=np.vstack((first_arr,second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [51]:
fifth_arr=np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
#Split array into 4 parts
sp_arr=np.array_split(fifth_arr,4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [53]:
print(sp_arr[1])

[4 5 6]


In [54]:
sp_arr=np.array_split(fifth_arr,8)
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [55]:
np.hsplit(third_2darr,5)

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [56]:
vs_arr=np.vsplit(third_2darr,2)
vs_arr

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

**Arithmetic Operations**

In [57]:
a=np.arange(1,11)
b=np.arange(21,31)

In [58]:
print(a+b)

print(b-a)
print(a*b)
print(a/b)

[22 24 26 28 30 32 34 36 38 40]
[20 20 20 20 20 20 20 20 20 20]
[ 21  44  69  96 125 156 189 224 261 300]
[0.04761905 0.09090909 0.13043478 0.16666667 0.2        0.23076923
 0.25925926 0.28571429 0.31034483 0.33333333]


In [59]:
b**a #b power a

array([             21,             484,           12167,          331776,
               9765625,       308915776,     10460353203,    377801998336,
        14507145975869, 590490000000000])

In [60]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [61]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [62]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [63]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [64]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [65]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [66]:
np.power(b,a)

array([             21,             484,           12167,          331776,
               9765625,       308915776,     10460353203,    377801998336,
        14507145975869, 590490000000000])

In [67]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

**Broadcasting**

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations.Subject to certain constraints,smaller array is broadcast across larger array so that they have compatible shapes.

In [68]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
b=np.arange(1,4)
b

array([1, 2, 3])

In [70]:
print(a+b)
#Now this was possible as both Arrays were compatible.First one is 3x3 and second one 1x3
#,so numpy for compatibility checks last 3 and does the required operations no of times multiple for first 1&3 so thrice

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [71]:
c=np.arange(1,3)
#print(a+c)
#ValueError: operands could not be broadcast together with shapes (3,3) (2,)

In [72]:
d=np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [73]:
e=np.arange(4)
e

array([0, 1, 2, 3])

In [74]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

**Aggregate Functions**


In [75]:
arr_1=np.arange(10,110,10)
arr_1


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [76]:
arr_2=np.arange(10,110,10).reshape(2,5)
arr_2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [77]:
arr_3=np.arange(10,130,10).reshape(4,3)
arr_3

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [78]:
#Aggregate Func - sum()
print(arr_1.sum())
print(arr_2.sum())
print(arr_3.sum())

550
550
780


In [79]:
#Columnwise Sum
print(arr_3.sum(axis=0))

#Rowise Sum
print(arr_3.sum(axis=1))

[220 260 300]
[ 60 150 240 330]


In [80]:
#Aggregate Func - prod()
arr_1.prod()

36288000000000000

In [81]:
#Columnwise product
print(arr_2.prod(axis=0))
#Rowise product
print(arr_2.prod(axis=1))

[ 600 1400 2400 3600 5000]
[  12000000 3024000000]


In [82]:
#Aggregate Func - avg,min,max,min,std

print("Average of elements in array 1 is :",np.average(arr_1))
print("Mean elements in array 1 is :",np.mean(arr_1))
print("Max of elements in array 1 is :",np.max(arr_1))
print("Min of elements in array 1 is :",np.min(arr_1))
print("Standard Deviation of elements in array 1 is :",np.std(arr_1))


Average of elements in array 1 is : 55.0
Mean elements in array 1 is : 55.0
Max of elements in array 1 is : 100
Min of elements in array 1 is : 10
Standard Deviation of elements in array 1 is : 28.722813232690143


**Unique Items & Counts**

In [83]:
first_arr=np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])
first_arr

array([ 1,  2,  3,  4,  5,  6,  1,  2,  7,  2,  1, 10,  7,  8])

In [84]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [85]:
second_arr=np.array([[1, 1, 2,1] ,[ 3, 1, 2,1] , [1, 1, 2, 1], [ 7, 1, 1, 1]])
second_arr


array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [86]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [87]:
np.unique(second_arr,axis=0)
#Removes duplicate row if any

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [88]:
np.unique(second_arr,axis=1)
#Removes duplicate column if any

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [89]:
np.unique(first_arr,return_index= True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 11]))

In [90]:
np.unique(second_arr,return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1]))