# Complete NumPy Tutorial 

![image.png](attachment:image.png)

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

a powerful N-dimensional array object

sophisticated (broadcasting) functions

tools for integrating C/C++ and Fortran code

useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Reference link: https://www.youtube.com/watch?v=GB9ByFAIAH4

![image.png](attachment:image.png)

![image.png](attachment:image.png)

![image.png](attachment:image.png)

![image.png](attachment:image.png)

In [25]:
a=[1,2,3] #array a and b as a list
b=[3,5,6]

In [26]:
a*b # can't multiply when arrays are declared as a list

TypeError: ignored

In [27]:
import numpy as np

In [28]:
c=np.array([1,2,3]) #initialize 1-D array
d=np.array([1,2,3])

In [29]:
c*d

array([1, 4, 9])

In [8]:
print(c)

[1 2 3]


In [30]:
#2-D array
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [12]:
c.shape

(3,)

In [13]:
#get Type
c.dtype

dtype('int64')

In [14]:
b.dtype

dtype('float64')

In [15]:
c=np.array([1,2,3], dtype='int16')

In [16]:
print(c)

[1 2 3]


In [17]:
#get size # item size for c is 2 bytes
c.itemsize

2

In [18]:
b.itemsize #each element is of 8 bytes in b

8

In [19]:
#Get total size
c.size

3

In [20]:
b.size

6

In [21]:
c.nbytes

6

In [22]:
b.nbytes

48

Accessing/ changing specific elements, rows, columns

In [ ]:
a=np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

In [ ]:
a.shape

In [ ]:
#Get a specific element [r,c]
a[1,5]

In [ ]:
#here, in python indexing starts at 0 so to access 13 we used index as [1,5]

In [ ]:
#here, in python indexing starts at 0 so to access 13 we used index as [1,5]
# also it is the second number from last in the second row therefore 
a[1,-2]

In [ ]:
#get a specific row
a[0,:]

In [ ]:
#get a specific column (say column with elts 3 and 10)
a[:,2] 

In [ ]:
#advanced [startindex: endindex:stepsize] 
#extract values 2 4 6 from first row
a[0,1:5:2]

In [ ]:
#advanced [startindex: endindex:stepsize] 
#extract values 2 4 6 from first row
a[0,1:6:2]

In [ ]:
a[0,1:-1:2]

In [ ]:
a[1,1:-1:2]

In [ ]:
#changing the value 13 in second row to 20
a[1,5]=20

In [ ]:
print(a)

In [ ]:
#change all the values to 5 in colummn having index 2
a[:,2]=5
print(a)

In [ ]:
a[:,2]=[1,2]
print(a)

3-D example

In [23]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#get specific element (work outside in)  # access value 4
b[0,1,1]

In [ ]:
b[:,1,:]

In [ ]:
b[:,1,0]

In [ ]:
b[:,0,:]

In [ ]:
b[:,0,0]

In [ ]:
#replace

b[:,1,:]=[[9,9],[8,8]] 
print("After replacing")
print(b)

Initialize different types of arrays 

In [ ]:
# all 0s matrix
np.zeros(5)

In [ ]:
np.zeros((2,3))

In [ ]:
np.zeros((2,3,3))

In [ ]:
np.zeros((2,3,3,2))

In [ ]:
np.zeros((2,3))

In [ ]:
#all 1's matrix
np.ones((4,2,2),dtype='int32')

In [ ]:
#any other number    
np.full((2,2),99)  #first arg is shape and second is value

In [ ]:
np.full((2,2),99, dtype='float32')

In [ ]:
a.shape

In [ ]:
#any other number (full-like)
np.full_like(a.shape,4)

In [ ]:
np.full_like(a,4)

In [ ]:
#initialize a matrix of random numbers #random number in the semi-open range [0.0, 1.0)
np.random.rand(4,2)

In [ ]:
np.random.rand(4,2,3)

In [ ]:
#generating the random numbers accroding to some shape
np.random.random_sample(a.shape)

In [ ]:
#random integer values 
np.random.randint(7, size=(3,3))

In [ ]:
np.random.randint(4,7, size=(3,3))

In [ ]:
np.random.randint(-4,8, size=(3,3))

In [ ]:
np.random.randint(-4,8, size=(3,3))

In [ ]:
np.identity(5) #identity matrix

In [ ]:
arr=np.array([1,2,3])
#repeat the array 3 times
r1=np.repeat(arr,3)
print(r1)

In [ ]:
arr=np.array([1,2,3]) 1-d array
arr.shape

In [ ]:
arr=np.array([[1,2,3]]) #2-D array
arr.shape

In [ ]:
arr=np.array([[1,2,3]]) #2-D
#repeat the array 3 times
r1=np.repeat(arr,3,axis=1) #along column
print(r1)

In [ ]:
arr=np.array([[1,2,3]]) #2-D
#repeat the array 3 times
r1=np.repeat(arr,3,axis=0)
print(r1)

![image.png](attachment:image.png)


Initialize the above matrix

In [31]:
arr=np.ones((5,5),dtype='int8')
print(arr)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [32]:
arr[1,1:4:1]=0
arr[2,1:4:1]=0
arr[3,1:4:1]=0
arr[2,2]=9
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [33]:
#another way
arr=np.ones((5,5),dtype='int8')
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
arr[1,1:4]=0
arr[2,1:4]=0
arr[3,1:4]=0
arr[2,2]=9
print(arr)

In [ ]:
#another way
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)


In [ ]:
#another way
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z   #first row to 3rd row (4 is exclusive) and same for column
print(output)

In [ ]:
# be care while copying arrays
a=np.array([1,2,3])
b=a

print("b is",b)
print ("a is", a)

b[0]=100

print("a is", a)

In [ ]:
# be careful while copying arrays
a=np.array([1,2,3])
b=a.copy()

print("b is",b)
print ("a is", a)

b[0]=100

print("a is", a)
print("b is",b)

Mathematics

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
print(a)

In [ ]:
a+2

In [ ]:
print(a)

In [ ]:
a-2

In [ ]:
a*2

In [ ]:
a/2

In [ ]:
b=np.array([1,0,1,0])
a+b

In [ ]:
a ** 2

In [ ]:
#take sin of all values 
np.sin(a)


In [ ]:
np.cos(a)

#####Linear Algebra

In [ ]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

In [ ]:
#find the determinant 
c=np.identity(3)
np.linalg.det(c)

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

statstics

In [ ]:
stats=np.array([[1,4,2],[4,0,6]])
stats

In [ ]:
np.min(stats)

In [ ]:
np.max(stats)

In [ ]:
np.min(stats,axis=0)

In [ ]:
np.min(stats,axis=1)

In [ ]:
np.sum(stats)

In [ ]:
np.sum(stats,axis=0)

In [ ]:
np.sum(stats,axis=1)

#reorganizing array

In [ ]:
before=np.array([[1,2,3,4], [5,6,7,8]])
print(before)

In [ ]:
print(before.shape)

In [ ]:
aft=before.reshape(8,1)
aft

# vertcially stacking vectors

In [ ]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])

In [ ]:
np.vstack([v1,v2,v1,v2])

In [ ]:
# horizontally stacking vectors


In [ ]:
h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack([h1,h2])

# Miscellaneous

In [ ]:
pwd

In [ ]:
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata

In [ ]:
#get data in int32 format
filedata=filedata.astype('int32')
filedata

## Advanced Indexing, Boolean masking

In [ ]:
filedata>50

In [ ]:
filedata[filedata>50]

## You can index with a list in Numpy

In [ ]:
a=np.array([10,20,30,40,50,60,70,80,90])
a[[1,2,8]]   #index 

In [ ]:
np.any(filedata>50 , axis=0)  #check vertically for 6 columns one by one if any value > 50 then true

In [ ]:
np.all(filedata>50 , axis=0)  #check vertically for 6 columns one by one if all value > 50 then true

In [ ]:
((filedata > 50) & (filedata <100))

In [ ]:
(~(filedata > 50) & (filedata <100))

 ![image.png](attachment:image.png)