<a href="https://colab.research.google.com/github/nachiket-15/Introduction_to_Data_Visualization/blob/main/numpy_linkedlearning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Essential Training**

**What is Numpy ?**

*NumPy (Numerical Python) is a powerful library in python which is used extensively for numerical and mathematical calculations*

**Applications**

*1.Multidimensional Arrays: NumPy provides a numpy.ndarray object, which is a multi-dimensional array. These arrays can be used to represent matrices, tensors, or any other multi-dimensional data structures.*

*2.Mathematical Operations: NumPy allows you to perform element-wise operations on arrays, making it easy to apply mathematical functions to entire datasets without the need for explicit loops.*

*3.Linear Algebra: NumPy provides a set of functions for linear algebra operations, such as matrix multiplication, inversion, determinant calculation, and more.*

*4.Broadcasting: NumPy supports broadcasting, which is a powerful mechanism that allows NumPy to work with arrays of different shapes and sizes during arithmetic operations.*

*5.Data Analysis and Manipulation: NumPy is often used in combination with other libraries like Pandas for data analysis and manipulation. It provides a foundation for working with numerical data efficiently.*


In [124]:
import numpy as np

In [125]:
list=[1,2,3,4,5,6,7]
arr=np.array(list)
print(arr)

arr=np.array([6,7,8,9,10,11,12])
print(arr)

[1 2 3 4 5 6 7]
[ 6  7  8  9 10 11 12]


In [126]:
#Third parameter is step/diff
arr1=np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]


In [127]:
#Third parameter is no of elements
arr2=np.linspace(1,10,5)
print(arr2)

[ 1.    3.25  5.5   7.75 10.  ]


In [128]:
print(arr2.dtype)
print(arr1.dtype)


float64
int64


In [129]:
arr3=np.random.rand(10)
print(arr3)

[0.17496939 0.46274813 0.51809021 0.31743919 0.88264891 0.33033803
 0.3074742  0.61351639 0.23764171 0.67262717]


In [130]:
arr4=np.random.rand(4,4)
print(arr4)

[[0.08176823 0.79288732 0.5619335  0.27929982]
 [0.67094795 0.78110033 0.68681019 0.46240759]
 [0.92517395 0.35808231 0.77741022 0.55407757]
 [0.08055184 0.24876356 0.668825   0.36835183]]


In [131]:
arr5=np.random.randint(1,100,25)
print(arr5)

[12 79 38 59 95 35 12 84 77 54 70 33 60 68  8  4 12 64 55  2 59 68 77 28
 54]


In [132]:
arr5

array([12, 79, 38, 59, 95, 35, 12, 84, 77, 54, 70, 33, 60, 68,  8,  4, 12,
       64, 55,  2, 59, 68, 77, 28, 54])

In [133]:
arr6=np.zeros(6)
print(arr6)

[0. 0. 0. 0. 0. 0.]


In [134]:
print(arr5.shape)
print(arr5.ndim)
print(arr4.shape)
print(arr4.ndim)

(25,)
1
(4, 4)
2


In [135]:
arr7=np.zeros((4,4),dtype=int)
print(arr7)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [136]:
arr8=np.ones(5,dtype=int)
print(arr8)

[1 1 1 1 1]


In [137]:
arr9=np.ones((5,5),dtype=int)
print(arr9)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [138]:
arr10=np.empty(6)
print(arr10)
arr10.fill(10)
print(arr10)

[0. 0. 0. 0. 0. 0.]
[10. 10. 10. 10. 10. 10.]


In [139]:
arr11=np.full(7,10)
print(arr11)

[10 10 10 10 10 10 10]


In [140]:
arr12=np.linspace((1,2),(10,20),10)
print(arr12)


[[ 1.  2.]
 [ 2.  4.]
 [ 3.  6.]
 [ 4.  8.]
 [ 5. 10.]
 [ 6. 12.]
 [ 7. 14.]
 [ 8. 16.]
 [ 9. 18.]
 [10. 20.]]


In [141]:
arr13=np.full((2,2,2),10)#tensor is a 3d array
print(arr13)


[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]


In [142]:
print(arr12.shape)
print(arr13.shape)
print(arr12.size)
print(arr13.size)
print(arr13.ndim)

(10, 2)
(2, 2, 2)
20
8
3


In [143]:

first_list=[1,2,3,4,5,6,7,8,9,10]
first_array=np.array(first_list)
print(first_array)

second_list=[1,2,3,-1.23,50,128000.56,4.56]
second_array=np.array(second_list)
print(second_array)
#print(second_array.dtype)

third_list=['Ann',111111,'Peter',111112,'Susan',111113,'John',111114]
third_array=np.array(third_list)
print(third_array)




[ 1  2  3  4  5  6  7  8  9 10]
[ 1.0000000e+00  2.0000000e+00  3.0000000e+00 -1.2300000e+00
  5.0000000e+01  1.2800056e+05  4.5600000e+00]
['Ann' '111111' 'Peter' '111112' 'Susan' '111113' 'John' '111114']


In [144]:
first_tuple=(5, 10, 15, 20, 25, 30)
array_from_tuple=np.array(first_tuple)
print(array_from_tuple)

print("\nTensor")
multi_dim_list=[[[0,1,2], [3,4,5]], [[6,7,8],[9,10,11]]]
arr_from_multi_dim_list=np.array(multi_dim_list)
print(arr_from_multi_dim_list)

[ 5 10 15 20 25 30]

Tensor
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


Adding , Removing & Sorting Elements

In [145]:
first_arr=np.array([1, 2, 3, 5])
print(first_arr)

new_first_arr=np.insert(first_arr,3,4)
print(new_first_arr)

[1 2 3 5]
[1 2 3 4 5]


In [146]:
second_arr=np.array([1,2,3,4])
print(second_arr)

new_second_arr=np.append(second_arr,5)
print(new_second_arr)

[1 2 3 4]
[1 2 3 4 5]


In [147]:
third_arr=np.array([1,2,3,4,5])
print(third_arr)

del_arr=np.delete(third_arr,4)
print(del_arr)

[1 2 3 4 5]
[1 2 3 4]


In [148]:
integers_arr=np.random.randint(0,20,20)
print(integers_arr)
print(np.sort(integers_arr))

print("\n")

integers_2dim_arr=np.array([[3, 2, 5,7, 4], [5, 0, 8,3, 1]])
print(integers_2dim_arr)
print(np.sort(integers_2dim_arr))

[16 15 11  7  6  8 18 18 11 19 18 14  5 13 13 17  7 17 11 19]
[ 5  6  7  7  8 11 11 11 13 13 14 15 16 17 17 18 18 18 19 19]


[[3 2 5 7 4]
 [5 0 8 3 1]]
[[2 3 4 5 7]
 [0 1 3 5 8]]


In [149]:
colors=np.array(['orange','green','yellow','white','black','pink','blue','red'])
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']


Copies & Views


In [150]:
#id() is often referred to as address of an object in python
students_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])

students_ids_number_reg=students_ids_number
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))

id of students_ids_number 134443456079376
id of students_ids_number_reg 134443456079376


In [151]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [152]:
#Creating a copy
students_ids_number_cp=students_ids_number.copy()
print(students_ids_number_cp)
print(students_ids_number_cp==students_ids_number)

[1111 2222 1313 1414 1515 1616 1717 1818]
[ True  True  True  True  True  True  True  True]


In [153]:
print ("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_cp",id(students_ids_number_cp))

id of students_ids_number 134443456079376
id of students_ids_number_cp 134443460073136


In [154]:
students_ids_number[0]=1000
print ("original: ", students_ids_number)
print("copy: ",students_ids_number_cp)

original:  [1000 2222 1313 1414 1515 1616 1717 1818]
copy:  [1111 2222 1313 1414 1515 1616 1717 1818]


In [155]:
students_ids_number_v=students_ids_number.view()

students_ids_number_v[0]=2000
print("original: ", students_ids_number)
print("view:",students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
view: [2000 2222 1313 1414 1515 1616 1717 1818]


In [156]:
print(students_ids_number_cp.base)
print(students_ids_number_v.base)


None
[2000 2222 1313 1414 1515 1616 1717 1818]


Main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

**Reshaping Arrays**

In [157]:
shape_array=np.arange(1,13)
print(shape_array)

print("\n")
nshape_array=np.reshape(shape_array,(6,2))
print(nshape_array)
print("\n")

nshape_array=np.reshape(shape_array,(4,3))
print(nshape_array)

print("\n")

nshape_array=np.reshape(shape_array,(3,2,2))
print(nshape_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [158]:
#Converting 2D array into 1D using reshape,flatten & ravel

sixth_arr=np.array([[1,2],[3,4],[5,6]])
print(sixth_arr)
print("\n")

seventh_arr_flat=np.reshape(sixth_arr,-1)
print("array_using_reshape",seventh_arr_flat)

eighth_arr_flat=sixth_arr.flatten()
print("\narr_using_flatten:",eighth_arr_flat)

ninth_arr_rav=sixth_arr.ravel()
print("\narr_using_ravel:",ninth_arr_rav)


#Reshape refers to chnaging shape of an array w/o changing data
#Flattening involves converting multi-dimensional array into one dimension
#FLatten returns copy of original array.Modifying flattened array does not changes original array
#Ravel returns reference/view of original array . Modifying ravelled array changes original array


[[1 2]
 [3 4]
 [5 6]]


array_using_reshape [1 2 3 4 5 6]

arr_using_flatten: [1 2 3 4 5 6]

arr_using_ravel: [1 2 3 4 5 6]


In [159]:
eighth_arr_flat[0]=100
print("sixth_arr:",sixth_arr)
print("eighth_arr_flat:",eighth_arr_flat)



sixth_arr: [[1 2]
 [3 4]
 [5 6]]
eighth_arr_flat: [100   2   3   4   5   6]


In [160]:
ninth_arr_rav[0]=300
print("ninth_arr_rav:",ninth_arr_rav)
print("sixth_arr:",sixth_arr)

ninth_arr_rav: [300   2   3   4   5   6]
sixth_arr: [[300   2]
 [  3   4]
 [  5   6]]


**Indexing and Slicing**

In [161]:
twodim_arr=np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
print(twodim_arr[1,1])
print(twodim_arr[1])

5
[4 5 6 7]


In [163]:
threedim_arr=np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [164]:
print(threedim_arr[0,2,3])
print("Indexing from end: ")
print(threedim_arr[2,-1,-1])

13
Indexing from end: 
59


In [165]:
onedim_arr=np.arange(10)
print(onedim_arr)
#Slicing [start,stop)
print(onedim_arr[2:6])
print(onedim_arr[:5])

#Last 3
print(onedim_arr[-3:])

#[Start,stop,step)
print(onedim_arr[::2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[0 1 2 3 4]
[7 8 9]
[0 2 4 6 8]


In [166]:
print(twodim_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [167]:
#Trimming 0th row and 0th column
print(twodim_arr[1:,1:])

#Printing 1st row
print(twodim_arr[1,:])

#Printing 2nd column
print(twodim_arr[:,2])


[[ 5  6  7]
 [ 9 10 11]]
[4 5 6 7]
[ 2  6 10]


In [171]:
first_arr=np.arange(1,11)
second_arr=np.arange(11,21)
print("first_arr",first_arr)
print("second_arr",second_arr)
con_arr=np.concatenate((first_arr,second_arr))
con_arr

first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr [11 12 13 14 15 16 17 18 19 20]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [172]:
third_2darr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(third_2darr)
fourth_2darr=np.array([[11,12,13,14,15], [16,17,18,19,20]])
print(fourth_2darr)

con2d_arr = np.concatenate((third_2darr,fourth_2darr),axis=1)
con2d_arr

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [173]:
st_arr = np.stack((first_arr,second_arr))
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])