In [1]:
import numpy as np


In [29]:
#Task 1 - Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
n=np.random.rand(25)

In [27]:
print(n)

[0.96319553 0.44496712 0.57821829 0.566054   0.35242752 0.16726129
 0.04857347 0.84562114 0.41126154 0.22917731 0.0328124  0.20630255
 0.70594634 0.13256386 0.58558596 0.20831625 0.41394765 0.44934291
 0.24018071 0.23445347 0.20560284 0.89665162 0.57750455 0.14301409
 0.06459043]


In [31]:
#Task 1 - Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
task1=np.random.normal(0,1,25)
task1


array([-0.04489168,  1.43011369,  0.00477014,  0.24642785,  1.4159728 ,
       -1.96099427,  1.76644691,  0.85450763, -0.08679854, -0.74935886,
        1.65565882,  0.07322784,  0.13672135, -1.48181866, -1.16829901,
       -1.27991356,  0.22062444,  0.04175577,  0.29382073,  0.21970287,
       -0.30717404,  0.67483238, -1.18419366, -1.76601634, -1.68137493])

In [5]:
#Task 2 - Create an array of 20 linearly spaced points between 0 and 1
task2=np.linspace(0, 1, 20)
task2

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [33]:
#Task 3 - Generating the given matrix
task3=np.arange(1,26).reshape(5,5)
task3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
#Task 3 - Get the standard deviation of the values in mat
std=np.std(task3)
std



7.211102550927978

In [8]:
#Task 3 - Sum of whole matrix 
sum=np.sum(task3)
sum

325

In [9]:
#Task 3 - Sum of Rows
sum_rows=np.sum(task3,axis=1)
sum_rows

array([ 15,  40,  65,  90, 115])

In [10]:
#Task 3 - Sum of columns 
sum_cols=np.sum(task3,axis=0)
sum_cols

array([55, 60, 65, 70, 75])

In [36]:
#Task 4 - Let X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]]). Get the diagonal of X, that is, [0, 5, 10]
task4=np.arange(0,12).reshape(3,4)
task4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
#Task 4 - Let X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]]). Get the diagonal of X, that is, [0, 5, 10]
d=np.diagonal(task4)
d

array([ 0,  5, 10])

In [13]:
#Task 5 - Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.
task5 = np.diag([1,2,3,4])
task5

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
#Task 6 - Create array which looks like below. array([[ 1, 2, 3], [ 4, 5, 6], [ 0, 8, 9], [ 0, 0,12]])
g = np.array([[ 1, 2, 3], [ 4, 5, 6], [ 0, 8, 9], [ 0, 0, 12]])
g

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [38]:
#Task 7 - Create a 5X2 integer array from a range between 100 to 200 such that the differencebetween each element is 10
h=np.arange(100,200,10).reshape(5,2)
h


array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [16]:
#Task 8 - Write a Program to check whether specified values are present in NumPy array
j = np.array([1,2,3,4])
print(j)
print(2 in j)
print(5 in j)


[1 2 3 4]
True
False


In [41]:
#Task 9 - Write a Program to calculate the sum of the diagonal elements of a NumPy array
k =np.arange(0,50,5)
k=k.reshape(2,5)
k
l=np.diagonal(k)
np.sum(l)


30

In [48]:
#Task 10 - Write a Program to Calculate the determinant of a matrix using NumPy
m=np.array([[12,24] , [25,45]])
np.linalg.det(m)



-60.000000000000036

In [56]:
#Task 11 -  Write a NumPy program to create an element-wise comparison (greater, greater_equal, less, and less_equal) of two given arrays
n=np.array([1,2])
o=np.array([3,4])
np.greater(n,o)


array([False, False])

In [58]:
np.greater_equal(n,o)

array([False, False])

In [54]:
np.less(n,o)

array([ True,  True])

In [59]:
np.less_equal(n,o)

array([ True,  True])

In [61]:
#Task 12 - Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0
p=np.ones((10,10))

p[1:-1,1:-1]=0

p



array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])